#!/usr/bin/env python3
"""Scan SukiSU source for missing linux/ and asm/ headers, create stubs.
Only create stub if the header doesn't exist in ANY include path."""
import os, re, glob

kernelsu_dir = "drivers/kernelsu"
if not os.path.isdir(kernelsu_dir):
    if os.path.islink(kernelsu_dir):
        kernelsu_dir = os.path.realpath(kernelsu_dir)

# All include paths in 4.9 kernel where headers might live
include_paths = [
    "include", "include/uapi", "include/generated",
    "arch/arm64/include", "arch/arm64/include/uapi",
    "arch/arm64/include/generated",
]

def header_exists(hdr):
    """Check if header exists in any include path."""
    for base in include_paths:
        if os.path.exists(os.path.join(base, hdr)):
            return True
    return False

# Headers that must NEVER be stubbed - they are generated during build
# or have special include chain behavior in 4.9 kernel
NEVER_STUB = {
    "linux/version.h",       # Generated by make, contains LINUX_VERSION_CODE
    "linux/kconfig.h",       # Generated, contains CONFIG_* macros
    "linux/generated/autoconf.h",  # Generated
}

stubs = []
for fp in glob.glob(os.path.join(kernelsu_dir, "**/*.c"), recursive=True) + \
        glob.glob(os.path.join(kernelsu_dir, "**/*.h"), recursive=True):
    try:
        content = open(fp).read()
    except:
        continue
    for m in re.finditer(r'#include\s+<(linux/[^>]+)>', content):
        hdr = m.group(1)
        if hdr in NEVER_STUB:
            continue
        if not header_exists(hdr):
            tgt = os.path.join("include", hdr)
            os.makedirs(os.path.dirname(tgt), exist_ok=True)
            n = hdr.replace("/", "_").replace(".", "_")
            open(tgt, "w").write("/* Stub 4.9 */\n#ifndef _%s_STUB\n#define _%s_STUB\n#endif\n" % (n, n))
            stubs.append(tgt)
    for m in re.finditer(r'#include\s+<(asm/[^>]+)>', content):
        hdr = m.group(1)
        if not header_exists(hdr):
            tgt = os.path.join("arch/arm64/include", hdr)
            os.makedirs(os.path.dirname(tgt), exist_ok=True)
            n = hdr.replace("/", "_").replace(".", "_")
            open(tgt, "w").write("/* Stub 4.9 */\n#ifndef _%s_STUB\n#define _%s_STUB\n#endif\n" % (n, n))
            stubs.append(tgt)

for s in sorted(set(stubs)):
    print("  Created: " + s)
print("Total stubs: %d" % len(set(stubs)))
